# Generated by Django 3.0.1 on 2019-12-30 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 31, 2, 53, 33, 775309))),
            ],
        ),
    ]
